### ISSUE TITLE
Delete svg image is missing in library list (Material skin)

### ISSUE THREAD

**Issue by cucko** [AF-1/lms-virtuallibrarycreator#3] opened 2024-02-27 11:17 UTC
## DESCRIBE THE BUG
Under: Custom virtual libraries created with this plugin, Delete icon is missing, Edit library is ok.

## TO REPRODUCE
1. Using Material Skin. go to Extras - Virtual Library Creator 
2. See the Delete icon is missing

## SCREENSHOTS
![image](https://github.com/AF-1/lms-virtuallibrarycreator/assets/653097/3c9f7e6d-56a3-44bc-b957-37a0169d0f65)

## VERSION INFO
* LMS version: Version: 8.5.0 - 1708878717 @ Mon Feb 26 02:14:25 CET 2024
* OS (version): Debian (Docker) - on RPi4
* Plugin version: 1.2.4
* Web skin/controller:     Material
* Browser (version): Chrome

## ADDITIONAL CONTEXT
Delete icon img src='http://192.168.1.223:9000/material/svg/plugins/VirtualLibraryCreator/html/images/html/images/vlc_delete.svg?svg=VirtualLibraryCreator&c=333'
while Edit icon img src='/material/svg/cs-edit?c=333'

**Comment by AF-1** [comment] 2024-02-27 15:47
I haven't been able to reproduce your issue with my Docker image (macOS, latest 8.5.0) and Material 4.3.3 (Light theme).

![dockersc](https://github.com/AF-1/lms-virtuallibrarycreator/assets/73786538/3457fb70-cad5-45da-83b8-93d374342848)

I've noticed though that your image src url for the delete gif seems to be missing “material“ between the 2 “html/images“. It should look sth like this:
`http://someipaddress:9000/material/svg/plugins/VirtualLibraryCreator/html/images/material/html/images/vlc_delete.svg?svg=VirtualLibraryCreator&c=333`

Maybe the author of the Material Skin plugin, @CDrummond, knows why your URL is different.

**Comment by CDrummond** [comment] 2024-02-27 16:19
This would appear to be an issue with Material. If Material is set as the default skin then this occurs. Will look into fixing this for 4.3.4 of MaterialSkin. I've raised on issue on Material's github for this.

**Comment by CDrummond** [comment] 2024-02-27 16:35
Fixed in next release of Material Skin.

**Closed** 2024-02-27 18:47 UTC
Labels: unable to replicate
