### ISSUE TITLE
[ISSUE] 

### ISSUE THREAD

**Issue by notDavid** [AF-1/lms-virtuallibrarycreator#1] opened 2023-06-27 19:50 UTC
Hi there,

We have created some Library Views, and every family member uses their own "View".

However, the active "View" constantly gets reset back to the `All Library (Default)` view, and we then have to `Home > Library Views > ...` to re-select the correct one again.
This is happening, whenever a "Library Scan" is triggered, looking for "New and changed media files".

Is this by design, or is it some misconfiguration at our end ?

Please advise... :-)
Thank you!

## EXPECTED BEHAVIOR
I expected, once i select a view via `Home > Library Views`, it will keep this view "forever" on that device (until i maybe one day select another one.)

## VERSION INFO
* LMS version:Logitech Media Server Version: 8.3.1 - 1676361197 @ Fri Feb 17 06:43:16 CET 2023
* OS (version): Operating system: Debian (Docker) - EN - utf8
* Platform Architecture: aarch64-linux
* Perl Version: 5.32.1 - aarch64-linux-gnu-thread-multi
* Plugin version: 1.0.4
* Web skin/controller:  Dark Default / iPeng
* Browser (version): Firefox 114.0.2

**Comment by AF-1** [comment] 2023-06-28 17:42
Thanks for reporting this.
Neither by design nor caused by anything you did. But certainly not what users want to see happing. 
I'm already looking into it... I'll post back when I know more.

**Comment by AF-1** [comment] 2023-07-02 19:01
Should be fixed. You'll need the latest VLC version (1.1.1) and an LMS version that contains the commit f05647e. 
The LMS fix is already part of the latest 8.**4**.0 version but I don't know when it'll be merged into the 8.**3**.0 branch.
And then it might take some time before it finds its way into the official stable version.
If you don't want to wait, here's a link to the frequently updated beta versions which I use exclusively: https://downloads.slimdevices.com/nightly/index.php

**Comment by AF-1** [comment] 2023-07-03 09:36
> Hopefully this Docker image also contains the fix?

I don't use Docker but it should. Docker `dev` = 8.4.0 branch.

**Comment by AF-1** [comment] 2023-07-10 16:13
Please let me know if 1.1.2 fixed this.

**Closed as completed** 2023-08-03 14:57 UTC
